name: 'CICD'
on: 
  push:
    branches:
      - main
jobs:
  cicd:
    runs-on: ubuntu-latest
    env:
      CI: true
    defaults:
      run:
        working-directory: standalone
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2

    - name: 'Setup NodeJS'
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: 'Install depenencies'
      run: yarn install

    - name: 'Run tests'
      run: yarn test

    - name: 'Set up QEMU'
      uses: docker/setup-qemu-action@v1

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v1

    - name: 'Login to DockerHub'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 'Build and push Docker image'
      uses: docker/build-push-action@v2
      with:
        context: ./standalone/
        file: ./standalone/Dockerfile
        push: true
        tags: robvanderleek/capture-website-api:latest

    - name: 'Deploy to Heroku (capture-website-api)'
      uses: akhileshns/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: 'capture-website-api'
        heroku_email: 'robvanderleek@gmail.com'
        usedocker: true

    - name: 'Deploy to Heroku (capture-website-api-patching)'
      uses: akhileshns/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: 'capture-website-api-patching'
        heroku_email: 'robvanderleek@gmail.com'
        usedocker: true
